/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    jacoco
}

group = "com.smartuxapi.ai"  // 그룹 ID 설정
version = "0.9.6"            // 프로젝트 버전 설정

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter test framework.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")

    // JUnit Platform Suite API (통합 테스트 스위트용)
    testImplementation("org.junit.platform:junit-platform-suite-api:1.10.1")
    testRuntimeOnly("org.junit.platform:junit-platform-suite-engine:1.10.1")

    // Mockito (단위 테스트 모킹 프레임워크)
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:33.2.1-jre")
    
    implementation("jakarta.servlet:jakarta.servlet-api:5.0.0")
    
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.3")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.3")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.3")
    
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("org.json:json:20250517")
    
    implementation("org.apache.logging.log4j:log4j-api:2.21.0")   // Log4j API
    implementation("org.apache.logging.log4j:log4j-core:2.21.0")  // Log4j Core
    
    // SnakeYAML (YAML 파일 파싱용)
    implementation("org.yaml:snakeyaml:2.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.jar {
    archiveFileName.set("${rootProject.name}-${project.version}.jar")
    
    manifest {
        attributes(
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Implementation-Vendor" to "Smart UX API",
            "Built-By" to System.getProperty("user.name"),
            "Built-JDK" to System.getProperty("java.version"),
            "Created-By" to "Gradle ${gradle.gradleVersion}"
        )
    }
}

// JavaDoc 설정
tasks.javadoc {
    options {
        this as StandardJavadocDocletOptions
        encoding = "UTF-8"
        charset("UTF-8")
        docEncoding = "UTF-8"
        
        // JavaDoc 옵션
        memberLevel = JavadocMemberLevel.PROTECTED
        links("https://docs.oracle.com/en/java/javase/17/docs/api/")
        
        // 경고 무시 (필요한 경우)
        addStringOption("Xdoclint:none", "-quiet")
        
        // 커스텀 태그
        tags(
            "apiNote:a:API Note:",
            "implSpec:a:Implementation Requirements:",
            "implNote:a:Implementation Note:"
        )
        
        // HTML5 출력
        addBooleanOption("html5", true)
        
        // 윈도우 제목
        windowTitle = "Smart UX API ${project.version} API Documentation"
        
        // 문서 제목
        docTitle = "Smart UX API ${project.version}"

        // 하단 텍스트 - addStringOption으로 설정
        addStringOption("bottom", "<div style='text-align: center;'>Copyright 2025 <a href='https://jiniebox.com'>jiniebox.com</a>. Licensed under the <a href='https://www.apache.org/licenses/LICENSE-2.0'>Apache License 2.0</a>.<br>Contact: <a href='mailto:kiunsea@gmail.com'>kiunsea@gmail.com</a> | Website: <a href='https://www.omnibuscode.com'>www.omnibuscode.com</a></div>")

        // 헤더 - addStringOption으로 설정
        addStringOption("header", "<b>Smart UX API ${project.version}</b><br><span style='font-size: 90%;'>AI-powered UI Automation</span>")
    }
    
    // 소스 파일 포함
    source = sourceSets["main"].allJava
    
    // 클래스패스 설정
    classpath = configurations["compileClasspath"]
}

// JavaDoc JAR 생성
tasks.register<Jar>("javadocJar") {
    group = "documentation"
    description = "Assembles a jar archive containing the JavaDoc."
    archiveClassifier.set("javadoc")
    from(tasks.javadoc)
}

// Sources JAR 생성
tasks.register<Jar>("sourcesJar") {
    group = "documentation"
    description = "Assembles a jar archive containing the main sources."
    archiveClassifier.set("sources")
    from(sourceSets["main"].allSource)
}

// Build 시 JavaDoc과 Sources JAR 생성
tasks.build {
    dependsOn("javadocJar", "sourcesJar")
}

// Test 리포트 설정
tasks.test {
    useJUnitPlatform()
    
    // 테스트 결과 리포트
    reports {
        html.required.set(true)
        junitXml.required.set(true)
    }
    
    // 테스트 로깅
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true // 테스트 출력 표시
        showExceptions = true
        showCauses = true
        showStackTraces = true
        minGranularity = 0 // 테스트 실행 시간 표시
    }
    
    // 테스트 실패 시에도 계속 실행
    ignoreFailures = false
    
    // 테스트 결과 요약 출력
    addTestListener(object : org.gradle.api.tasks.testing.TestListener {
        override fun beforeSuite(suite: org.gradle.api.tasks.testing.TestDescriptor) {}
        override fun afterSuite(suite: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {
            if (suite.parent == null) {
                println("\n" + "=".repeat(80))
                println("테스트 결과 요약")
                println("=".repeat(80))
                println("총 테스트: ${result.testCount}")
                println("성공: ${result.successfulTestCount}")
                println("실패: ${result.failedTestCount}")
                println("건너뜀: ${result.skippedTestCount}")
                println("실행 시간: ${result.endTime - result.startTime}ms")
                println("=".repeat(80))
                println("상세 리포트: build/reports/tests/test/index.html")
                println("=".repeat(80) + "\n")
            }
        }
        override fun beforeTest(testDescriptor: org.gradle.api.tasks.testing.TestDescriptor) {}
        override fun afterTest(testDescriptor: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {}
    })
}

// JaCoCo 코드 커버리지 설정
tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)

    reports {
        xml.required.set(true)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/test/html"))
    }
}

// ============================================================
// deploy 태스크: JAR 빌드 및 배포
// ============================================================

tasks.register("deploy") {
    group = "distribution"
    description = "JAR를 빌드하고 doribox와 smuxapi-demo에 배포합니다."
    
    dependsOn("jar")
    
    // 배포 대상 디렉터리 (lib 모듈 기준 상대 경로)
    // v0.9.2 평탄화 후: lib/ → repo root(..)  → github(../..) → ../../doribox
    val doriboxLibsDir = file("../../doribox/libs")
    
    doFirst {
        println("=".repeat(60))
        println("🚀 smart-ux-api 배포 프로세스 시작")
        println("=".repeat(60))
        println("배포 대상:")
        println("  - doribox: ${doriboxLibsDir.absolutePath}")
        println()
    }
    
    doLast {
        val jarTask = tasks.named<Jar>("jar").get()
        val jarFile = jarTask.archiveFile.get().asFile
        
        if (!jarFile.exists()) {
            throw GradleException("JAR 파일을 찾을 수 없습니다: ${jarFile.absolutePath}")
        }
        
        println("[1/4] 빌드된 JAR 파일 확인")
        println("   -> ${jarFile.name} (${String.format("%.2f", jarFile.length() / 1024.0 / 1024.0)} MB)")
        println()
        
        // 3. doribox libs에서 이전 버전 JAR 삭제
        println("[2/4] doribox libs에서 이전 버전 JAR 삭제 중...")
        if (doriboxLibsDir.exists()) {
            val deletedCount = doriboxLibsDir.listFiles { file ->
                file.isFile && file.name.startsWith("smart-ux-api-") && file.name.endsWith(".jar")
            }?.count { oldJar ->
                println("   -> 삭제: ${oldJar.name}")
                oldJar.delete()
            } ?: 0
            if (deletedCount == 0) {
                println("   -> 삭제할 이전 버전이 없습니다.")
            }
        } else {
            println("   -> 경고: doribox libs 디렉터리가 없습니다: ${doriboxLibsDir.absolutePath}")
            println("      (디렉터리를 생성합니다)")
            doriboxLibsDir.mkdirs()
        }
        println()
        
        // 4. 최신 JAR 복사
        println("[4/4] 최신 JAR 복사 중...")
              
        // doribox에 복사
        val targetDoriboxJar = file("${doriboxLibsDir.absolutePath}/${jarFile.name}")
        jarFile.copyTo(targetDoriboxJar, overwrite = true)
        println("   -> doribox: ${targetDoriboxJar.absolutePath}")
        
        println()
        println("=".repeat(60))
        println("✅ 배포 완료!")
        println("=".repeat(60))
        println()
        println("📦 배포된 JAR 파일:")
        println("   이름: ${jarFile.name}")
        println("   크기: ${String.format("%.2f", jarFile.length() / 1024.0 / 1024.0)} MB")
        println()
        println("📂 배포 위치:")
        println("   - doribox: ${targetDoriboxJar.absolutePath}")
        println()
        println("=".repeat(60))
    }
}